---

#  - name: Copy slurm files
#    synchronize: mode=pull src={{ item }} dest=/root/rpmbuild/RPMS/x86_64/
#    delegate_to: slurm-service
#    with_items:
#         - "/root/rpmbuild/RPMS/x86_64/slurm-plugins-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-perlapi-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-slurmdb-direct-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-sql-{{ slurm_version }}-1.el6.x86_64.rpm"
         #- "roles/slurm_common/files/slurm-lua-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-pam_slurm-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-sjstat-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-slurmdbd-{{ slurm_version }}-1.el6.x86_64.rpm"
         #- "roles/slurm_common/files/slurm-spank-x11-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-torque-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-devel-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-munge-{{ slurm_version }}-1.el6.x86_64.rpm"
#         - "/root/rpmbuild/RPMS/x86_64/slurm-sjobexit-{{ slurm_version }}-1.el6.x86_64.rpm"



  - name:  distribute the slurm RPMs to the nodes
    copy: src={{ item }}
           dest=/root/rpmbuild/RPMS/x86_64/ 
    with_items:
         - "roles/slurm_common/files/slurm-plugins-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-perlapi-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-slurmdb-direct-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-sql-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-lua-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-devel-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-pam_slurm-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-sjstat-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-slurmdbd-{{ slurm_version }}-1.el6.x86_64.rpm"
        #- "roles/slurm_common/files/slurm-spank-x11-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-torque-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-munge-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "roles/slurm_common/files/slurm-sjobexit-{{ slurm_version }}-1.el6.x86_64.rpm"


  - name: install Slurm
    #yum: name="/root/rpmbuild/RPMS/x86_64/{{ item }}-{{ slurm_version }}-1.el6.x86_64.rpm" state=present
    yum: name={{ item }} state=present
    tags: slurm
    with_items:

         - "/root/rpmbuild/RPMS/x86_64/slurm-plugins-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-perlapi-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-slurmdb-direct-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-sql-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-lua-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-devel-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-pam_slurm-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-sjstat-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-slurmdbd-{{ slurm_version }}-1.el6.x86_64.rpm"
         #- "/root/rpmbuild/RPMS/x86_64/slurm-spank-x11-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-torque-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-munge-{{ slurm_version }}-1.el6.x86_64.rpm"
         - "/root/rpmbuild/RPMS/x86_64/slurm-sjobexit-{{ slurm_version }}-1.el6.x86_64.rpm"


  - name: pam.d/slurm
    copy: src=slurm dest=/etc/pam.d/slurm owner=root mode="644"
    tags: slurm
 

  - name: slurm.conf
    template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf owner=root mode="644"
    tags: slurm
   
  - name: add slurm user
    user: name=slurm shell=/sbin/nologin createhome=no home=/nonexixtent system=yes append=yes
    tags: slurm
   
  - name: add slurm log dir
    file: path="/var/log/slurm" state=directory owner=slurm group=slurm mode=750
    tags: slurm

  - name: add slurm tmp dir
    file: path="/tmp/slurmd" state=directory owner=slurm group=slurm mode=750
    tags: slurm

  - name: add slurm tmp dir
    file: path="/tmp/slurmstate" state=directory owner=slurm group=slurm mode=750
    tags: slurm


