---
    - name: update all packages first
      yum: pkg=* state=latest

    - name: Remove duplicate CentOS repos
      file: name=/etc/yum.repos.d/centos6-latest.repo state=absent
      when: major_relase is "6"

    - name: install EPEL6
      yum: name='http://www.nic.funet.fi/pub/mirrors/fedora.redhat.com/pub/epel/6/i386/epel-release-6-8.noarch.rpm' state=present
      when: major_relase is "6"

    - name: install software required to build slurm
      yum: name="{{item}}" state=present
      with_items:
        - "xterm"
        - "sssd"
        - "gcc" 
        - "make"
        - "gcc-c++"
        - "wget"
        - "vim"
        - "man"
        - "rpm-build"
        - "pam"
        - "pam-devel"
        - "hwloc"
        - "hwloc-devel"
        - "munge"
        - "munge-devel"
        - "munge-libs"
        - "readline-devel"
        - "openssl-devel"
        - "perl-ExtUtils-MakeMaker"
        - "lua"
        - "lua-devel"
        - "lua-posix"
        - "lua-filesystem"

    - debug: msg="{{groups['all']}}"
      tags: debug
