---
# This sh/could be put in a separate role..
  - name: Add FGI slurm repo
    template: src=fgislurm.repo dest=/etc/yum.repos.d/fgislurm.repo owner=root group=root mode=0644 backup=yes
    when: fgci_install == True

  - name: Import FGI slurm repo key
    rpm_key: key=http://idris.fgi.csc.fi/fgirepo6/RPM-GPG-KEY-CSC-GRID-2 state=present
    when: fgci_install == True

  - name: Install FGCI repo 
    yum: pkg=http://idris.fgi.csc.fi/fgci7/x86_64/fgci/rpms/fgci-release7-1-1.el7.noarch.rpm
    when: ansible_distribution_major_version == "7" and fgci_install == True

##

  - name: install Slurm on non-compute nodes
    yum: name={{ item }} state=present
    with_items: slurm_packages
    when: slurm_type != "compute" and slurm_packages.0 != ""

  - name: install Slurm on compute nodes
    yum: name={{ item }} state=present
    with_items: slurm_node_packages
    when: slurm_type == "compute" and slurm_node_packages.0 != ""

  - name: install fgci Slurm addons
    yum: name=slurm-fgi-addons state=present
    when: fgci_install and ansible_distribution_major_version == "7"

  - name: pam.d/slurm
    copy: src=pam_slurm dest=/etc/pam.d/slurm owner=root mode=0644
 
  - name: slurm.conf
    template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf owner=root mode=0644 backup=yes
   
  - name: add slurm unix user
    user: name=slurm shell=/sbin/nologin createhome=no home=/nonexixtent system=yes append=yes

  - name: write all slurm logs handled by rsyslog to one file
    template: src=slurm_rsyslog.conf dest=/etc/rsyslog.d/10_slurm_rsyslog.conf owner=root mode=0644 backup=yes
   
  - name: add slurm log dir
    file: "path={{ slurm_log_dir }} state=directory owner=slurm group=slurm mode=0750"

  - name: add slurm tmp dir
    file: "path={{ slurmd_tmp_dir }} state=directory owner=slurm group=slurm mode=0750"

  - name: add slurm state dir
    file: "path={{ slurm_state_dir }} state=directory owner=slurm group=slurm mode=0750"


