---

  - name: get munge key for distribution to nodes
    copy: src=files/munge.key
          dest=/etc/munge/munge.key
          owner=munge
          group=munge
          mode=400

  - name: start and enable munge
    service: name=munge state=restarted enabled=yes

  - name: start and enable slurm
    service: name=slurm state=restarted enabled=yes
