---

  - name: get munge key for distribution to nodes
    copy: src=files/munge.key
          dest=/etc/munge/munge.key
          owner=munge
          group=munge
          mode=400
    when: slurm_munge_key_from_nfs == False

  - name: copy the munge key from NFS
    command: cp -v {{ slurm_munge_key_nfs }} /etc/munge/munge.key
    when: slurm_munge_key_from_nfs == True

  - name: set permissions on the munge key from NFS
    file: path=/etc/munge/munge.key mode=0400 owner=munge group=munge
    when: slurm_munge_key_from_nfs == True

  - name: start and enable munge
    service: name=munge state=restarted enabled=yes

  - name: start and enable slurm on EL6
    service: name=slurm state=restarted enabled=yes
    when: ansible_distribution_major_version == "6"

  - name: start and enable slurmD on EL7
    service: name=slurmd state=restarted enabled=yes
    when: ansible_distribution_major_version == "7"
