---

# tasks file for ansible-role-slurm
# Order matters.
#

- name: Slurm OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml


- include: build.yml
  when: slurm_build == True and slurm_type == "service" and ansible_os_family == "RedHat"

- include: common.yml
  when: ansible_os_family == "RedHat"

- include: dbd.yml
  when: (slurm_accounting_storage_host == ansible_hostname) and ansible_os_family == "RedHat"

- include: service.yml
  when: slurm_type == "service" and ansible_os_family == "RedHat"

- include: compute.yml
  when: slurm_type == "compute" and ansible_os_family == "RedHat"

- include: submit.yml
  when: slurm_type == "submit" and ansible_os_family == "RedHat"
