---

  - name: get munge key for distribution to nodes
    copy: src=files/munge.key
          dest=/etc/munge/munge.key
          owner=munge
          group=munge
          mode=400
          
  - name: start munge
    service: name=munge state=restarted enabled=yes

