---
    - name: update all packages first
      yum: pkg=* state=latest

    - name: Remove duplicate CentOS repos
      file: name=/etc/yum.repos.d/centos6-latest.repo state=absent

    - name: install EPEL6
      yum: name='http://www.nic.funet.fi/pub/mirrors/fedora.redhat.com/pub/epel/6/i386/epel-release-6-8.noarch.rpm' state=present
      when: major_relase is "6"

    - name: install software
      yum: name="{{item}}" state=present
      with_items:
        - "xterm"
        - "sssd"
        - "gcc" 
        - "make"
        - "gcc-c++"
        - "wget"
        - "vim"
        - "man"
        - "rpm-build"
        - "pam"
        - "pam-devel"
        - "hwloc"
        - "munge"
        - "munge-devel"
        - "munge-libs"
        - "readline-devel"
        - "openssl-devel"
        - "perl-ExtUtils-MakeMaker"
        - "lua"
        - "lua-devel"
        - "lua-posix"
        - "lua-filesystem"

    - debug: msg="{{groups['all']}}"
      tags: debug



#    - name: create /etc/hosts
#      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{item}}" state=present
#      when: hostvars[item]['ansible_default_ipv4']['address'] is defined
#      with_items: groups['all']
#      tags: debug

    - name: Add cluster hosts to local /etc/hosts
      sudo: yes
      action: lineinfile
        state=present
        dest=/etc/hosts
        line="{{ hostvars[item]['ssh_host'] }} {{ item }}"
      when: hostvars[item]['ssh_host'] is defined
      with_items: groups.all
      tags: debug

    - name: copy iptables settings
      copy: src=iptables
            dest=/etc/sysconfig/iptables owner=root mode=600


    - name: restart iptables
      service: name=iptables state=restarted
